### ISSUE TITLE
AssertionError: Invalid command byte 10

### ISSUE THREAD

**Issue by cechurat** [bmrzycki/gw1000-http#1]
Hi Brian,

First of all, let me thank you for your contribution to the qw1000 REST API server.

I can list the weather station - it works fine. But I run into issues when performing a request - I got the error "AssertionError: Invalid command byte 10". I can see that there is no command 10 since the commands are in hex format ("LIVEDATA") but I have no idea how can I affect it in any way. Please, can you give me a clue? Thank you for your help.

Kind Regards,
Tomas

(running on up-to-date Raspberry Pi OS Bullseye with Python 3.9)

![image](https://user-images.githubusercontent.com/22544220/189497705-3d87391d-2ccf-4528-9521-98288cc624e0.png)

**Comment by bmrzycki** [comment]
Hello Tomas,

Thanks for the kind words and for using the software. :)

I think I have a fix for you pushed to the head of the repository. I updated the Livedata byte list: it's grown considerably in size since I first created the tool.

By default I ignore all the devices I don't own: I can't debug them if I don't have the hardware.

Hopefully this will get you going.

**Comment by cechurat** [comment]
Hello Brian,

Thank you for your quick response! It is working like a charm now.

Thank you and have a nice day!

Cheers, Tomas
